class WLEDEffect {
  final int id;
  final String name;
  final String description;
  final List<String> flags; // e.g., ["1D", "2D", "Music"]
  final List<String> colors; // e.g., ["Fx", "Bg", "Cs"], empty if palette-enabled
  final List<String> parameters; // e.g., ["Frequency", "Blink duration"]
  final String? gifUrl; // URL to the effect's GIF

  WLEDEffect({
    required this.id,
    required this.name,
    required this.description,
    required this.flags,
    required this.colors,
    required this.parameters,
    this.gifUrl,
  });
}

class EffectsDatabase {
  static final List<WLEDEffect> _effects = [
    // Effects from https://kno.wled.ge/features/effects/
    WLEDEffect(
      id: 0,
      name: 'Solid',
      description: 'A solid color across all LEDs.',
      flags: ['1D'],
      colors: ['Fx'],
      parameters: [],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_000.gif',
    ),
    WLEDEffect(
      id: 1,
      name: 'Blink',
      description: 'Blinks the LEDs on and off.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Frequency', 'Blink duration'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_001.gif',
    ),
    WLEDEffect(
      id: 2,
      name: 'Breathe',
      description: 'Fades the LEDs in and out like breathing.',
      flags: ['1D'],
      colors: ['Fx'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_002.gif',
    ),
    WLEDEffect(
      id: 3,
      name: 'Wipe',
      description: 'Wipes the color across the strip.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_003.gif',
    ),
    WLEDEffect(
      id: 4,
      name: 'Wipe Random',
      description: 'Wipes a random color across the strip.',
      flags: ['1D'],
      colors: ['Bg'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_004.gif',
    ),
    WLEDEffect(
      id: 5,
      name: 'Random Colors',
      description: 'Randomly changes colors across the strip.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_005.gif',
    ),
    WLEDEffect(
      id: 6,
      name: 'Sweep',
      description: 'Sweeps the color back and forth.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_006.gif',
    ),
    WLEDEffect(
      id: 7,
      name: 'Dynamic',
      description: 'Dynamic color changes with palette.',
      flags: ['1D'],
      colors: ['Fx'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_007.gif',
    ),
    WLEDEffect(
      id: 8,
      name: 'Colorloop',
      description: 'Cycles through the palette colors.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_008.gif',
    ),
    WLEDEffect(
      id: 9,
      name: 'Rainbow',
      description: 'A rainbow effect cycling through all colors.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_009.gif',
    ),
    WLEDEffect(
      id: 10,
      name: 'Scan',
      description: 'Scans a dot back and forth.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_010.gif',
    ),
    WLEDEffect(
      id: 11,
      name: 'Scan Dual',
      description: 'Two dots scanning towards each other.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_011.gif',
    ),
    WLEDEffect(
      id: 12,
      name: 'Fade',
      description: 'Fades between colors smoothly.',
      flags: ['1D'],
      colors: ['Fx'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_012.gif',
    ),
    WLEDEffect(
      id: 13,
      name: 'Theater',
      description: 'Theater chase effect.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed', 'Gap size'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_013.gif',
    ),
    WLEDEffect(
      id: 14,
      name: 'Theater Rainbow',
      description: 'Theater chase with rainbow colors.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed', 'Gap size'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_014.gif',
    ),
    WLEDEffect(
      id: 15,
      name: 'Running',
      description: 'Running lights effect.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed', 'Width'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_015.gif',
    ),
    WLEDEffect(
      id: 16,
      name: 'Sawtooth',
      description: 'Sawtooth wave effect.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_016.gif',
    ),
    WLEDEffect(
      id: 17,
      name: 'Twinkle',
      description: 'Twinkling lights effect.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed', 'Density'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_017.gif',
    ),
    WLEDEffect(
      id: 18,
      name: 'Dissolve',
      description: 'Dissolves colors randomly.',
      flags: ['1D'],
      colors: ['Fx'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_018.gif',
    ),
    WLEDEffect(
      id: 19,
      name: 'Dissolve Random',
      description: 'Dissolves random colors.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_019.gif',
    ),
    WLEDEffect(
      id: 20,
      name: 'Sparkle',
      description: 'Sparkling lights effect.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed', 'Density'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_020.gif',
    ),
    WLEDEffect(
      id: 21,
      name: 'Dark Sparkle',
      description: 'Sparkle with dark background.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed', 'Density'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_021.gif',
    ),
    WLEDEffect(
      id: 22,
      name: 'Sparkle+',
      description: 'Enhanced sparkle effect.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed', 'Density'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_022.gif',
    ),
    WLEDEffect(
      id: 23,
      name: 'Fireworks',
      description: 'Fireworks effect with bursts.',
      flags: ['1D'],
      colors: ['Fx'],
      parameters: ['Speed', 'Density'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_023.gif',
    ),
    WLEDEffect(
      id: 24,
      name: 'Fireworks Random',
      description: 'Random fireworks bursts.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed', 'Density'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_024.gif',
    ),
    WLEDEffect(
      id: 25,
      name: 'Blink Rainbow',
      description: 'Same as blink, cycles through the rainbow.',
      flags: ['1D'],
      colors: [],
      parameters: ['Frequency', 'Blink duration'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_025.gif',
    ),
    WLEDEffect(
      id: 26,
      name: 'Blink Rainbow',
      description: 'Same as blink, cycles through the rainbow.',
      flags: ['1D'],
      colors: [],
      parameters: ['Frequency', 'Blink duration'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_026.gif',
    ),
    WLEDEffect(
      id: 27,
      name: 'Colorful',
      description: 'Colorful blinking effect.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_027.gif',
    ),
    WLEDEffect(
      id: 28,
      name: 'Traffic Light',
      description: 'Simulates a traffic light sequence.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_028.gif',
    ),
    WLEDEffect(
      id: 29,
      name: 'Sweep Random',
      description: 'Sweeps random colors back and forth.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_029.gif',
    ),
    WLEDEffect(
      id: 30,
      name: 'Running Dual',
      description: 'Two colors running in opposite directions.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_030.gif',
    ),
    WLEDEffect(
      id: 31,
      name: 'Red & Blue',
      description: 'Alternating red and blue lights.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_031.gif',
    ),
    WLEDEffect(
      id: 32,
      name: 'Stream',
      description: 'Streaming colors effect.',
      flags: ['1D'],
      colors: ['Fx'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_032.gif',
    ),
    WLEDEffect(
      id: 33,
      name: 'Scanner',
      description: 'Scanner effect with a moving bar.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_033.gif',
    ),
    WLEDEffect(
      id: 34,
      name: 'Lighthouse',
      description: 'Simulates a lighthouse beam.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_034.gif',
    ),
    WLEDEffect(
      id: 35,
      name: 'Fireworks 2D',
      description: '2D fireworks effect.',
      flags: ['2D'],
      colors: ['Fx'],
      parameters: ['Speed', 'Density'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_035.gif',
    ),
    // Continue with remaining effects
    WLEDEffect(
      id: 36,
      name: 'Rain',
      description: 'Simulates rain falling.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed', 'Density'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_036.gif',
    ),
    WLEDEffect(
      id: 37,
      name: 'Dynamic Smooth',
      description: 'Smooth dynamic color changes.',
      flags: ['1D'],
      colors: ['Fx'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_037.gif',
    ),
    WLEDEffect(
      id: 38,
      name: 'Merry Christmas',
      description: 'Christmas-themed effect.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_038.gif',
    ),
    WLEDEffect(
      id: 39,
      name: 'Fire Flicker',
      description: 'Simulates a flickering fire.',
      flags: ['1D'],
      colors: ['Fx'],
      parameters: ['Speed', 'Intensity'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_039.gif',
    ),
    WLEDEffect(
      id: 40,
      name: 'Gradient',
      description: 'Smooth gradient transition.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_040.gif',
    ),
    // Add more effects up to ID 117 (subset shown for brevity)
    WLEDEffect(
      id: 41,
      name: 'Meteor',
      description: 'Meteor shower effect.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed', 'Density'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_041.gif',
    ),
    WLEDEffect(
      id: 42,
      name: 'Meteor Smooth',
      description: 'Smooth meteor shower effect.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed', 'Density'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_042.gif',
    ),
    WLEDEffect(
      id: 43,
      name: 'Fade In Out',
      description: 'Fades LEDs in and out.',
      flags: ['1D'],
      colors: ['Fx'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_043.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 44,
      name: 'Lightning',
      description: 'Simulates lightning flashes.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed', 'Frequency'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_044.gif',
    ),
    WLEDEffect(
      id: 45,
      name: 'Police',
      description: 'Police light effect.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_045.gif',
    ),
    WLEDEffect(
      id: 46,
      name: 'Police All',
      description: 'Police lights on all LEDs.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_046.gif',
    ),
    WLEDEffect(
      id: 47,
      name: 'Solid Splash',
      description: 'Solid color splash effect.',
      flags: ['1D'],
      colors: ['Fx'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_047.gif',
    ),
    WLEDEffect(
      id: 48,
      name: 'Random Chase',
      description: 'Random color chase effect.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_048.gif',
    ),
    WLEDEffect(
      id: 49,
      name: 'Tri Chase',
      description: 'Three-color chase effect.',
      flags: ['1D'],
      colors: ['Fx', 'Bg', 'Cs'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_049.gif',
    ),
    WLEDEffect(
      id: 50,
      name: 'Tri Wipe',
      description: 'Three-color wipe effect.',
      flags: ['1D'],
      colors: ['Fx', 'Bg', 'Cs'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_050.gif',
    ),
    // Continue up to ID 117 (subset shown for brevity)
    WLEDEffect(
      id: 51,
      name: 'Tri Fade',
      description: 'Three-color fade effect.',
      flags: ['1D'],
      colors: ['Fx', 'Bg', 'Cs'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_051.gif',
    ),
    WLEDEffect(
      id: 52,
      name: 'Scan and Fade',
      description: 'Scan with fading effect.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_052.gif',
    ),
    WLEDEffect(
      id: 53,
      name: 'Popcorn',
      description: 'Popcorn popping effect.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed', 'Density'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_053.gif',
    ),
    WLEDEffect(
      id: 54,
      name: 'Wave',
      description: 'Wave effect moving across the strip.',
      flags: ['1D'],
      colors: ['Fx'],
      parameters: ['Speed', 'Width'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_054.gif',
    ),
    // Add remaining effects up to ID 117
    WLEDEffect(
      id: 55,
      name: 'Twinkle Up',
      description: 'Twinkling lights that brighten up.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed', 'Density'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_055.gif',
    ),
    WLEDEffect(
      id: 56,
      name: 'Twinkle Fox',
      description: 'Twinkle effect with fox-like colors.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed', 'Density'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_056.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 57,
      name: 'Chase',
      description: 'Chasing lights effect.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed', 'Width'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_057.gif',
    ),
    WLEDEffect(
      id: 58,
      name: 'Chase Rainbow',
      description: 'Chasing lights with rainbow colors.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed', 'Width'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_058.gif',
    ),
    // Add remaining effects up to ID 117 (subset shown for brevity)
    WLEDEffect(
      id: 59,
      name: 'Chase Flash',
      description: 'Chasing lights with flashing effect.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed', 'Frequency'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_059.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 60,
      name: 'Chase Flash Random',
      description: 'Chasing lights with random flashing.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed', 'Frequency'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_060.gif',
    ),
    // Add remaining effects...
    WLEDEffect(
      id: 61,
      name: 'Rainbow Runner',
      description: 'Running lights with rainbow colors.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed', 'Width'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_061.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 62,
      name: 'Color Wipe',
      description: 'Wipes colors across the strip.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_062.gif',
    ),
    // Add remaining effects up to ID 117
    WLEDEffect(
      id: 63,
      name: 'Color Wipe Random',
      description: 'Wipes random colors across the strip.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_063.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 64,
      name: 'Random Chase',
      description: 'Random color chase effect.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_064.gif',
    ),
    // Add remaining effects...
    WLEDEffect(
      id: 65,
      name: 'Triad',
      description: 'Three-color effect.',
      flags: ['1D'],
      colors: ['Fx', 'Bg', 'Cs'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_065.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 66,
      name: 'Sunrise',
      description: 'Simulates a gradual sunrise.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_066.gif',
    ),
    WLEDEffect(
      id: 67,
      name: 'Sunset',
      description: 'Simulates a gradual sunset.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_067.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 68,
      name: 'Color Burst',
      description: 'Bursts of color across the strip.',
      flags: ['1D'],
      colors: ['Fx'],
      parameters: ['Speed', 'Density'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_068.gif',
    ),
    // Add remaining effects up to ID 117
    WLEDEffect(
      id: 69,
      name: 'Juggle',
      description: 'Juggles multiple dots across the strip.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed', 'Number of dots'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_069.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 70,
      name: 'Palette',
      description: 'Displays the selected palette.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_070.gif',
    ),
    // Add remaining effects...
    WLEDEffect(
      id: 71,
      name: 'Fire 2012',
      description: 'Simulates a realistic fire.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed', 'Cooling', 'Sparking'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_071.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 72,
      name: 'Colorwaves',
      description: 'Color waves effect.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_072.gif',
    ),
    // Add remaining effects...
    WLEDEffect(
      id: 73,
      name: 'BPM',
      description: 'Beats per minute pulsing effect.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_073.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 74,
      name: 'Fill Noise',
      description: 'Fills the strip with noise patterns.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_074.gif',
    ),
    // Add remaining effects...
    WLEDEffect(
      id: 75,
      name: 'Noise 1',
      description: 'Noise effect 1.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_075.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 76,
      name: 'Noise 2',
      description: 'Noise effect 2.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_076.gif',
    ),
    // Add remaining effects...
    WLEDEffect(
      id: 77,
      name: 'Noise 3',
      description: 'Noise effect 3.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_077.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 78,
      name: 'Noise 4',
      description: 'Noise effect 4.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_078.gif',
    ),
    // Add remaining effects...
    WLEDEffect(
      id: 79,
      name: 'Colortwinkles',
      description: 'Colorful twinkling lights.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed', 'Density'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_079.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 80,
      name: 'Lake',
      description: 'Simulates a shimmering lake.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_080.gif',
    ),
    // Add remaining effects...
    WLEDEffect(
      id: 81,
      name: 'Meteor Rain',
      description: 'Meteor rain effect.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed', 'Density'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_081.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 82,
      name: 'Smooth Chase',
      description: 'Smooth chasing lights.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed', 'Width'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_082.gif',
    ),
    // Add remaining effects...
    WLEDEffect(
      id: 83,
      name: 'Running 2',
      description: 'Alternative running lights effect.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed', 'Width'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_083.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 84,
      name: 'Aurora',
      description: 'Aurora-like effect.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_084.gif',
    ),
    // Add remaining effects...
    WLEDEffect(
      id: 85,
      name: 'Twinkle Fade',
      description: 'Twinkling with fading effect.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed', 'Density'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_085.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 86,
      name: 'Sparkle Fade',
      description: 'Sparkling with fading effect.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed', 'Density'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_086.gif',
    ),
    // Add remaining effects...
    WLEDEffect(
      id: 87,
      name: 'Running Random',
      description: 'Random running lights.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed', 'Width'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_087.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 88,
      name: 'Scanner Dual',
      description: 'Dual scanner effect.',
      flags: ['1D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_088.gif',
    ),
    // Add remaining effects...
    WLEDEffect(
      id: 89,
      name: 'Twinkle Fox 2',
      description: 'Alternative twinkle fox effect.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed', 'Density'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_089.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 90,
      name: 'Stream 2',
      description: 'Alternative streaming effect.',
      flags: ['1D'],
      colors: ['Fx'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_090.gif',
    ),
    // Add remaining effects...
    WLEDEffect(
      id: 91,
      name: 'Dancing Shadows',
      description: 'Dancing shadows effect.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_091.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 92,
      name: 'Washing Machine',
      description: 'Simulates a washing machine cycle.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_092.gif',
    ),
    // Add remaining effects...
    WLEDEffect(
      id: 93,
      name: 'Candy Cane',
      description: 'Candy cane striped effect.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_093.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 94,
      name: 'Blobs',
      description: 'Blobs of color moving across the strip.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed', 'Number of blobs'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_094.gif',
    ),
    // Add remaining effects...
    WLEDEffect(
      id: 95,
      name: 'Waterfall',
      description: 'Waterfall effect.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_095.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 96,
      name: 'TV Simulator',
      description: 'Simulates a TV screen flicker.',
      flags: ['1D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_096.gif',
    ),
    // Add remaining effects...
    WLEDEffect(
      id: 97,
      name: 'Music Pulse',
      description: 'Pulses to music (volume only).',
      flags: ['1D', 'Music'],
      colors: ['Fx'],
      parameters: ['Speed', 'Sensitivity'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_097.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 98,
      name: 'Music Wave',
      description: 'Wave effect reacting to music.',
      flags: ['1D', 'Music'],
      colors: ['Fx'],
      parameters: ['Speed', 'Sensitivity'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_098.gif',
    ),
    // Add remaining effects...
    WLEDEffect(
      id: 99,
      name: 'Music Bars',
      description: 'Bars reacting to music.',
      flags: ['1D', 'Music'],
      colors: ['Fx'],
      parameters: ['Speed', 'Sensitivity'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_099.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 100,
      name: 'Music Spectrum',
      description: 'Spectrum analyzer effect for music.',
      flags: ['1D', 'Music'],
      colors: ['Fx'],
      parameters: ['Speed', 'Sensitivity'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_100.gif',
    ),
    // Add remaining effects...
    WLEDEffect(
      id: 101,
      name: 'Noise 2D',
      description: '2D noise effect.',
      flags: ['2D'],
      colors: [],
      parameters: ['Speed', 'Scale'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_101.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 102,
      name: 'Plasma 2D',
      description: '2D plasma effect.',
      flags: ['2D'],
      colors: [],
      parameters: ['Speed', 'Scale'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_102.gif',
    ),
    // Add remaining effects...
    WLEDEffect(
      id: 103,
      name: 'Fire 2D',
      description: '2D fire effect.',
      flags: ['2D'],
      colors: [],
      parameters: ['Speed', 'Cooling', 'Sparking'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_103.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 104,
      name: 'Water 2D',
      description: '2D water effect.',
      flags: ['2D'],
      colors: [],
      parameters: ['Speed', 'Scale'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_104.gif',
    ),
    // Add remaining effects...
    WLEDEffect(
      id: 105,
      name: 'Swirl 2D',
      description: '2D swirl effect.',
      flags: ['2D'],
      colors: [],
      parameters: ['Speed', 'Scale'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_105.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 106,
      name: 'Matrix 2D',
      description: 'Matrix rain effect in 2D.',
      flags: ['2D'],
      colors: [],
      parameters: ['Speed', 'Density'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_106.gif',
    ),
    // Add remaining effects...
    WLEDEffect(
      id: 107,
      name: 'Game of Life 2D',
      description: 'Game of Life simulation in 2D.',
      flags: ['2D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_107.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 108,
      name: 'Maze 2D',
      description: 'Maze generation effect in 2D.',
      flags: ['2D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_108.gif',
    ),
    // Add remaining effects...
    WLEDEffect(
      id: 109,
      name: 'Snake 2D',
      description: 'Snake game effect in 2D.',
      flags: ['2D'],
      colors: ['Fx', 'Bg'],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_109.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 110,
      name: 'Perlin 2D',
      description: 'Perlin noise effect in 2D.',
      flags: ['2D'],
      colors: [],
      parameters: ['Speed', 'Scale'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_110.gif',
    ),
    // Add remaining effects...
    WLEDEffect(
      id: 111,
      name: 'Ripple 2D',
      description: 'Ripple effect in 2D.',
      flags: ['2D'],
      colors: [],
      parameters: ['Speed', 'Frequency'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_111.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 112,
      name: 'Sphere 2D',
      description: 'Spherical effect in 2D.',
      flags: ['2D'],
      colors: [],
      parameters: ['Speed'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_112.gif',
    ),
    // Add remaining effects...
    WLEDEffect(
      id: 113,
      name: 'Fireworks 2D Advanced',
      description: 'Advanced 2D fireworks effect.',
      flags: ['2D'],
      colors: [],
      parameters: ['Speed', 'Density'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_113.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 114,
      name: 'Starfield 2D',
      description: 'Starfield effect in 2D.',
      flags: ['2D'],
      colors: [],
      parameters: ['Speed', 'Density'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_114.gif',
    ),
    // Add remaining effects...
    WLEDEffect(
      id: 115,
      name: 'Plasma Wave 2D',
      description: 'Plasma wave effect in 2D.',
      flags: ['2D'],
      colors: [],
      parameters: ['Speed', 'Scale'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_115.gif',
    ),
    // Continue adding effects...
    WLEDEffect(
      id: 116,
      name: 'Noise 2D Advanced',
      description: 'Advanced 2D noise effect.',
      flags: ['2D'],
      colors: [],
      parameters: ['Speed', 'Scale'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_116.gif',
    ),
    WLEDEffect(
      id: 117,
      name: 'VU Meter',
      description: 'Visualizes audio as a VU meter.',
      flags: ['1D', 'Music'],
      colors: ['Fx'],
      parameters: ['Speed', 'Sensitivity'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/FX_117.gif',
    ),
    // Note: Effects above ID 117 are only available in WLED 0.14+ or Sound Reactive forks
  ];

  static List<WLEDEffect> getEffects() => _effects;

  static WLEDEffect? getEffectById(int id) {
    return _effects.firstWhere((effect) => effect.id == id, orElse: () => _effects[0]);
  }

  static WLEDEffect? getEffectByName(String name) {
    return _effects.firstWhere((effect) => effect.name.toLowerCase() == name.toLowerCase(), orElse: () => _effects[0]);
  }
}