class WLEDPalette {
  final int id;
  final String name;
  final String description;
  final List<String>? colors; // Only for palettes 0-5, null for others
  final String? gifUrl; // URL to the palette's GIF

  WLEDPalette({
    required this.id,
    required this.name,
    required this.description,
    this.colors,
    this.gifUrl,
  });
}

class PalettesDatabase {
  static final List<WLEDPalette> _palettes = [
    // Standard palettes from WLED documentation (IDs 0-60)
    WLEDPalette(
      id: 0,
      name: 'Default',
      description: 'The palette is automatically selected depending on the effect. For most effects, this is the primary color.',
      colors: ['Primary'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_000.gif',
    ),
    WLEDPalette(
      id: 1,
      name: 'Random Cycle',
      description: 'The palette changes to a random one every few seconds. Subject to change.',
      colors: [], // Colors vary randomly
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_001.gif',
    ),
    WLEDPalette(
      id: 2,
      name: 'Color 1',
      description: 'A palette consisting only of the primary color.',
      colors: ['Primary'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_002.gif',
    ),
    WLEDPalette(
      id: 3,
      name: 'Colors 1&2',
      description: 'Consists of the primary and secondary color.',
      colors: ['Primary', 'Secondary'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_003.gif',
    ),
    WLEDPalette(
      id: 4,
      name: 'Color Gradient',
      description: 'A palette which is a mixture of all segment colors.',
      colors: ['Primary', 'Secondary', 'Tertiary'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_004.gif',
    ),
    WLEDPalette(
      id: 5,
      name: 'Colors Only',
      description: 'Contains primary, secondary and tertiary colors.',
      colors: ['Primary', 'Secondary', 'Tertiary'],
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_005.gif',
    ),
    // From ID 6 onwards, exclude the colors field
    WLEDPalette(
      id: 6,
      name: 'Party',
      description: 'Rainbow without green hues.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_006.gif',
    ),
    WLEDPalette(
      id: 7,
      name: 'Cloud',
      description: 'Gray-blueish colors.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_007.gif',
    ),
    WLEDPalette(
      id: 8,
      name: 'Lava',
      description: 'Dark red, yellow and bright white.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_008.gif',
    ),
    WLEDPalette(
      id: 9,
      name: 'Ocean',
      description: 'Blue, teal and white colors.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_009.gif',
    ),
    WLEDPalette(
      id: 10,
      name: 'Forest',
      description: 'Yellow and green hues.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_010.gif',
    ),
    WLEDPalette(
      id: 11,
      name: 'Rainbow',
      description: 'Every hue.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_011.gif',
    ),
    WLEDPalette(
      id: 12,
      name: 'Rainbow Bands',
      description: 'Rainbow colors with black spots in-between.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_012.gif',
    ),
    WLEDPalette(
      id: 13,
      name: 'Sunset',
      description: 'Dark blue with purple, red and yellow hues.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_013.gif',
    ),
    WLEDPalette(
      id: 14,
      name: 'Rivendell',
      description: 'Desaturated greens.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_014.gif',
    ),
    WLEDPalette(
      id: 15,
      name: 'Breeze',
      description: 'Teal colors with varying brightness.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_015.gif',
    ),
    WLEDPalette(
      id: 16,
      name: 'Red & Blue',
      description: 'Red running on blue.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_016.gif',
    ),
    WLEDPalette(
      id: 17,
      name: 'Yellowout',
      description: 'Yellow, fading out.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_017.gif',
    ),
    WLEDPalette(
      id: 18,
      name: 'Analogous',
      description: 'Red running on blue.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_018.gif',
    ),
    WLEDPalette(
      id: 19,
      name: 'Splash',
      description: 'Vibrant pink and magenta.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_019.gif',
    ),
    WLEDPalette(
      id: 20,
      name: 'Pastel',
      description: 'Different hues with very little saturation.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_020.gif',
    ),
    WLEDPalette(
      id: 21,
      name: 'Sunset 2',
      description: 'Yellow and white running on dim blue.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_021.gif',
    ),
    WLEDPalette(
      id: 22,
      name: 'Beach',
      description: 'Different shades of light blue.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_022.gif',
    ),
    WLEDPalette(
      id: 23,
      name: 'Vintage',
      description: 'Warm white running on very dim red.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_023.gif',
    ),
    WLEDPalette(
      id: 24,
      name: 'Departure',
      description: 'Greens and white fading out.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_024.gif',
    ),
    WLEDPalette(
      id: 25,
      name: 'Landscape',
      description: 'Blue, white and green gradient.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_025.gif',
    ),
    WLEDPalette(
      id: 26,
      name: 'Beech',
      description: 'Teal and yellow gradient fading out.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_026.gif',
    ),
    WLEDPalette(
      id: 27,
      name: 'Sherbet',
      description: 'Bright white, pink and mint colors.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_027.gif',
    ),
    WLEDPalette(
      id: 28,
      name: 'Hult',
      description: 'White, magenta and teal.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_028.gif',
    ),
    WLEDPalette(
      id: 29,
      name: 'Hult 64',
      description: 'Teal and yellow hues.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_029.gif',
    ),
    WLEDPalette(
      id: 30,
      name: 'Drywet',
      description: 'Blue and yellow gradient.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_030.gif',
    ),
    WLEDPalette(
      id: 31,
      name: 'Jul',
      description: 'Pastel green and red.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_031.gif',
    ),
    WLEDPalette(
      id: 32,
      name: 'Grintage',
      description: 'Yellow fading out.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_032.gif',
    ),
    WLEDPalette(
      id: 33,
      name: 'Rewhi',
      description: 'Bright orange on desaturated purple.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_033.gif',
    ),
    WLEDPalette(
      id: 34,
      name: 'Tertiary',
      description: 'Red, green and blue gradient.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_034.gif',
    ),
    WLEDPalette(
      id: 35,
      name: 'Fire',
      description: 'White, yellow and fading red gradient.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_035.gif',
    ),
    WLEDPalette(
      id: 36,
      name: 'Icefire',
      description: 'Same as Fire, but with blue colors.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_036.gif',
    ),
    WLEDPalette(
      id: 37,
      name: 'Cyane',
      description: 'Desaturated pastel colors.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_037.gif',
    ),
    WLEDPalette(
      id: 38,
      name: 'Light Pink',
      description: 'Desaturated purple hues.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_038.gif',
    ),
    WLEDPalette(
      id: 39,
      name: 'Autumn',
      description: 'Three white fields surrounded by yellow and dim red.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_039.gif',
    ),
    WLEDPalette(
      id: 40,
      name: 'Magenta',
      description: 'White with magenta and blue.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_040.gif',
    ),
    WLEDPalette(
      id: 41,
      name: 'Magred',
      description: 'Magenta and red hues.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_041.gif',
    ),
    WLEDPalette(
      id: 42,
      name: 'Yelmag',
      description: 'Magenta and red hues with a yellow.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_042.gif',
    ),
    WLEDPalette(
      id: 43,
      name: 'Yelblu',
      description: 'Blue with a little yellow.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_043.gif',
    ),
    WLEDPalette(
      id: 44,
      name: 'Orange & Teal',
      description: 'An Orange - Gray - Teal gradient.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_044.gif',
    ),
    WLEDPalette(
      id: 45,
      name: 'Tiamat',
      description: 'A bright meteor with blue, teal and magenta hues.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_045.gif',
    ),
    WLEDPalette(
      id: 46,
      name: 'April Night',
      description: 'Dark blue background with colorful snowflakes.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_046.gif',
    ),
    WLEDPalette(
      id: 47,
      name: 'Orangery',
      description: 'Orange and yellow tones.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_047.gif',
    ),
    WLEDPalette(
      id: 48,
      name: 'C9',
      description: 'Christmas lights palette. Red - amber - green - blue.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_048.gif',
    ),
    WLEDPalette(
      id: 49,
      name: 'Sakura',
      description: 'Pink and rose tones.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_049.gif',
    ),
    WLEDPalette(
      id: 50,
      name: 'Aurora',
      description: 'Greens on dark blue.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_050.gif',
    ),
    WLEDPalette(
      id: 51,
      name: 'Atlantica',
      description: 'Greens & Blues of the ocean.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_051.gif',
    ),
    WLEDPalette(
      id: 52,
      name: 'C9 2',
      description: 'C9 plus yellow.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_052.gif',
    ),
    WLEDPalette(
      id: 53,
      name: 'C9 New',
      description: 'C9, but brighter and with a less purple blue.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_053.gif',
    ),
    WLEDPalette(
      id: 54,
      name: 'Temperature',
      description: 'Temperature mapping.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_054.gif',
    ),
    WLEDPalette(
      id: 55,
      name: 'Aurora 2',
      description: 'Aurora with some pinks & blue.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_055.gif',
    ),
    WLEDPalette(
      id: 56,
      name: 'Retro Clown',
      description: 'Yellow to purple gradient.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_056.gif',
    ),
    WLEDPalette(
      id: 57,
      name: 'Candy',
      description: 'Vivid yellows, magenta, salmon and blues.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_057.gif',
    ),
    WLEDPalette(
      id: 58,
      name: 'Toxy Reaf',
      description: 'Vivid aqua to purple gradient.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_058.gif',
    ),
    WLEDPalette(
      id: 59,
      name: 'Fairy Reaf',
      description: 'Bright aqua to purple gradient.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_059.gif',
    ),
    WLEDPalette(
      id: 60,
      name: 'Semi Blue',
      description: 'Dark blues with a bright blue burst.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_060.gif',
    ),
    // Additional palettes to fill the gap (IDs 61-70)
    WLEDPalette(
      id: 61,
      name: 'Pink Candy',
      description: 'White, pinks and purple',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_061.gif',
    ),
    WLEDPalette(
      id: 62,
      name: 'Emerald',
      description: 'A rich palette of emerald greens and deep teals, inspired by precious gemstones.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_062.gif',
    ),
    WLEDPalette(
      id: 63,
      name: 'Sapphire',
      description: 'A luxurious palette of deep blues and silvers, evoking the sparkle of sapphires.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_063.gif',
    ),
    WLEDPalette(
      id: 64,
      name: 'Amethyst',
      description: 'A regal palette of purples and lavenders, inspired by the amethyst gemstone.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_064.gif',
    ),
    WLEDPalette(
      id: 65,
      name: 'Golden',
      description: 'A luxurious palette of golds and yellows, creating a warm and opulent display.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_065.gif',
    ),
    WLEDPalette(
      id: 66,
      name: 'Sunflower',
      description: 'A bright palette of yellows and greens, inspired by the vibrant colors of sunflowers in a field.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_066.gif',
    ),
    WLEDPalette(
      id: 67,
      name: 'Orchid',
      description: 'A delicate palette of purples, pinks, and whites, evoking the elegance of orchid flowers.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_067.gif',
    ),
    WLEDPalette(
      id: 68,
      name: 'Storm',
      description: 'A dramatic palette of dark grays, blues, and purples, capturing the intensity of a stormy sky.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_068.gif',
    ),
    WLEDPalette(
      id: 69,
      name: 'Candy Cane',
      description: 'A festive palette of red and white stripes, reminiscent of classic candy canes.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_069.gif',
    ),
    WLEDPalette(
      id: 70,
      name: 'Candy2',
      description: 'Faded gradient of yellow, salmon and blue',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_070.gif',
    ),
    // Custom palettes (supported as of WLED 0.14, IDs 71-80)
    WLEDPalette(
      id: 71,
      name: 'Custom 0',
      description: 'User-uploaded custom palette 0, allowing for a personalized color selection.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_071.gif',
    ),
    WLEDPalette(
      id: 72,
      name: 'Custom 1',
      description: 'User-uploaded custom palette 1, allowing for a personalized color selection.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_072.gif',
    ),
    WLEDPalette(
      id: 73,
      name: 'Custom 2',
      description: 'User-uploaded custom palette 2, allowing for a personalized color selection.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_073.gif',
    ),
    WLEDPalette(
      id: 74,
      name: 'Custom 3',
      description: 'User-uploaded custom palette 3, allowing for a personalized color selection.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_074.gif',
    ),
    WLEDPalette(
      id: 75,
      name: 'Custom 4',
      description: 'User-uploaded custom palette 4, allowing for a personalized color selection.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_075.gif',
    ),
    WLEDPalette(
      id: 76,
      name: 'Custom 5',
      description: 'User-uploaded custom palette 5, allowing for a personalized color selection.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_076.gif',
    ),
    WLEDPalette(
      id: 77,
      name: 'Custom 6',
      description: 'User-uploaded custom palette 6, allowing for a personalized color selection.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_077.gif',
    ),
    WLEDPalette(
      id: 78,
      name: 'Custom 7',
      description: 'User-uploaded custom palette 7, allowing for a personalized color selection.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_078.gif',
    ),
    WLEDPalette(
      id: 79,
      name: 'Custom 8',
      description: 'User-uploaded custom palette 8, allowing for a personalized color selection.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_079.gif',
    ),
    WLEDPalette(
      id: 80,
      name: 'Custom 9',
      description: 'User-uploaded custom palette 9, allowing for a personalized color selection.',
      colors: null,
      gifUrl: 'https://raw.githubusercontent.com/scottrbailey/WLED-Utils/master/gifs/PAL_080.gif',
    ),
  ];

  static List<WLEDPalette> getPalettes() => _palettes;

  static WLEDPalette? getPaletteById(int id) {
    return _palettes.firstWhere((palette) => palette.id == id, orElse: () => _palettes[0]);
  }

  static WLEDPalette? getPaletteByName(String name) {
    return _palettes.firstWhere((palette) => palette.name.toLowerCase() == name.toLowerCase(), orElse: () => _palettes[0]);
  }
}