import 'package:flutter/material.dart';
import 'effects_database.dart';
import 'palettes_database.dart';

class Preset {
  final String name;
  final String description;
  final IconData icon;
  final List<String> categories;
  final int fx; // Changed from effectName to fx
  final List<String>? colors;
  final int? paletteId;
  final int? sx;
  final int? ix;
  final int? c1;
  final int? c2;
  final int? c3;
  final bool? o1;
  final bool? o2;
  final bool? o3;
  bool isSelected;

  Preset({
    required this.name,
    required this.description,
    required this.icon,
    required this.categories,
    required this.fx, // Changed from effectName to fx
    this.colors,
    this.paletteId,
    this.sx,
    this.ix,
    this.c1,
    this.c2,
    this.c3,
    this.o1,
    this.o2,
    this.o3,
    this.isSelected = false,
  });

  Map<String, dynamic> toSettings() {
    return {
      'effect': fx, // Updated to use fx number
      if (colors != null && colors!.isNotEmpty) 'colors': colors,
      if (paletteId != null) 'palette': paletteId,
      if (sx != null) 'speed': sx,
      if (ix != null) 'intensity': ix,
      if (c1 != null) 'custom1': c1,
      if (c2 != null) 'custom2': c2,
      if (c3 != null) 'custom3': c3,
      if (o1 != null) 'option1': o1,
      if (o2 != null) 'option2': o2,
      if (o3 != null) 'option3': o3,
    };
  }

  String getEffect() {
    final effect = EffectsDatabase.effectsDatabase.firstWhere(
      (e) => e['id'] == fx, // Updated to match by fx number
      orElse: () => {'name': 'Unknown'},
    );
    return effect['name'] as String;
  }

  String getColorsOrPalette() {
    if (colors != null && colors!.isNotEmpty) {
      String hexColor = colors![0].replaceAll('#', '');
      if (hexColor.length == 6) return '#$hexColor';
      return '#FFFFFF';
    }
    if (paletteId != null) {
      final palette = PalettesDatabase.palettesDatabase.firstWhere(
        (p) => p['id'] == paletteId,
        orElse: () => {'name': 'Unknown'},
      );
      return 'Palette: ${palette['name'] as String}';
    }
    return 'No Palette';
  }
}

class PresetDatabase {
  static final List<Preset> _presets = [
    // **Test Presets**
    Preset(
      name: 'Rainbow Flow',
      description: 'A flowing rainbow effect across all LEDs.',
      icon: Icons.color_lens,
      categories: ['Test'],
      fx: 9,
      paletteId: 0,
      sx: 128,
      ix: 128,
    ),
    Preset(
      name: '2 Color Pattern',
      description: 'A pattern alternating between two colors.',
      icon: Icons.pattern,
      categories: ['Test'],
      fx: 83,
      colors: ['0000FF', 'FFC800', '0000FF'],
      paletteId: 0,
      sx: 30,
      ix: 30,
    ),
    Preset(
      name: '3 Color Pattern',
      description: 'A pattern alternating between three colors.',
      icon: Icons.pattern,
      categories: ['Test'],
      fx: 84,
      colors: ['FF0000', '08FF00', '0000FF'],
      paletteId: 0,
      sx: 100,
      ix: 30,
    ),
    Preset(
      name: '2 Color Chase',
      description: 'A chasing effect with two colors.',
      icon: Icons.directions_run,
      categories: ['Test'],
      fx: 37,
      colors: ['0000FF', 'FFC800', '0000FF'],
      paletteId: 0,
      sx: 30,
      ix: 30,
    ),
    Preset(
      name: '3 Color Chase',
      description: 'A chasing effect with three colors.',
      icon: Icons.directions_run,
      categories: ['Test'],
      fx: 54,
      colors: ['FF0000', '08FF00', '0000FF'],
      paletteId: 0,
      sx: 30,
      ix: 30,
    ),
    Preset(
      name: 'Cool red thing',
      description: 'A cool red effect with a dynamic flow.',
      icon: Icons.waves,
      categories: ['Test'],
      fx: 94,
      colors: ['EABE92', '000000', 'FFC800'],
      paletteId: 4,
      sx: 30,
      ix: 0,
    ),
    Preset(
      name: 'Fun run',
      description: 'A fun running effect with vibrant colors.',
      icon: Icons.directions_run,
      categories: ['Test'],
      fx: 111,
      colors: ['FF0000', '000000', 'B700B7'],
      paletteId: 1,
      sx: 22,
      ix: 142,
    ),
    Preset(
      name: 'Sinelon Rainbow',
      description: 'A sinelon effect with rainbow colors.',
      icon: Icons.color_lens,
      categories: ['Test'],
      fx: 94,
      colors: ['EABE92', '000000', 'FFC800'],
      paletteId: 0,
      sx: 146,
      ix: 9,
    ),
    Preset(
      name: 'Preset 1',
      description: 'A dynamic preset with vibrant colors.',
      icon: Icons.lightbulb,
      categories: ['Test'],
      fx: 116,
      colors: ['FF0000', '000000', 'B700B7'],
      paletteId: 1,
      sx: 223,
      ix: 171,
    ),
    Preset(
      name: 'Preset 2',
      description: 'Another dynamic preset with vibrant colors.',
      icon: Icons.lightbulb,
      categories: ['Test'],
      fx: 115,
      colors: ['FF0000', '000000', 'B700B7'],
      paletteId: 1,
      sx: 18,
      ix: 171,
    ),
    Preset(
      name: 'Preset 3',
      description: 'A third dynamic preset with vibrant colors.',
      icon: Icons.lightbulb,
      categories: ['Test'],
      fx: 137,
      colors: ['FF0000', '000000', 'B700B7'],
      paletteId: 1,
      sx: 18,
      ix: 171,
    ),

    // **Accents**
    Preset(
      name: 'Accent Lights 1x1',
      description: 'Subtle white accent lighting.',
      icon: Icons.light,
      categories: ['Accents'],
      fx: 83,
      colors: ['FFFFFF', '000000', '000000'],
      paletteId: 0,
      sx: 10,
      ix: 10,
    ),
    Preset(
      name: 'Accent Lights 2x2',
      description: 'Moderate white accent lighting.',
      icon: Icons.light,
      categories: ['Accents'],
      fx: 83,
      colors: ['FFFFFF', '000000', '000000'],
      paletteId: 0,
      sx: 30,
      ix: 30,
    ),
    Preset(
      name: 'Accent Lights 5x3',
      description: 'Bright white accent lighting.',
      icon: Icons.light,
      categories: ['Accents'],
      fx: 83,
      colors: ['FFFFFF', '000000', '000000'],
      paletteId: 0,
      sx: 90,
      ix: 50,
    ),
    Preset(
      name: 'Accent Warm 1x1',
      description: 'Subtle warm accent lighting.',
      icon: Icons.light,
      categories: ['Accents'],
      fx: 83,
      colors: ['FFE0A0', '000000', '000000'],
      paletteId: 0,
      sx: 10,
      ix: 10,
    ),
    Preset(
      name: 'Accent Warm 2x2',
      description: 'Moderate warm accent lighting.',
      icon: Icons.light,
      categories: ['Accents'],
      fx: 83,
      colors: ['FFE0A0', '000000', '000000'],
      paletteId: 0,
      sx: 30,
      ix: 30,
    ),
    Preset(
      name: 'Accent Warm 5x3',
      description: 'Bright warm accent lighting.',
      icon: Icons.light,
      categories: ['Accents'],
      fx: 83,
      colors: ['FFE0A0', '000000', '000000'],
      paletteId: 0,
      sx: 90,
      ix: 50,
    ),
    Preset(
      name: 'Accent Dim Bright Dim',
      description: 'Dim to bright white accent lighting.',
      icon: Icons.light,
      categories: ['Accents'],
      fx: 84,
      colors: ['FFFFFF', '3C3C3C', '3C3C3C'],
      paletteId: 0,
      sx: 128,
      ix: 11,
    ),
    Preset(
      name: 'Starlight',
      description: 'A starlight effect with warm tones.',
      icon: Icons.star,
      categories: ['Accents'],
      fx: 16,
      colors: ['683808', 'D8A878', '000000'],
      paletteId: 2,
      sx: 52,
      ix: 122,
    ),
    Preset(
      name: 'Prismatic Switch',
      description: 'A prismatic color-switching effect.',
      icon: Icons.color_lens,
      categories: ['Accents'],
      fx: 86,
      colors: ['FFFFFF', '60605D', '000000'],
      paletteId: 1,
      sx: 0,
      ix: 255,
    ),
    Preset(
      name: 'Icy Breezy',
      description: 'Cool blue tones like a refreshing breeze.',
      icon: Icons.waves,
      categories: ['Accents'],
      fx: 43,
      colors: ['95BFE9', '133D67', '000000'],
      paletteId: 7,
      sx: 41,
      ix: 91,
    ),
    Preset(
      name: 'Golden Dawn',
      description: 'Warm golden tones of a sunrise.',
      icon: Icons.wb_sunny,
      categories: ['Accents'],
      fx: 94,
      colors: ['EABE92', '663A0E', '000000'],
      paletteId: 4,
      sx: 30,
      ix: 0,
    ),
    Preset(
      name: 'Autumn Leaves',
      description: 'Warm tones of falling autumn leaves.',
      icon: Icons.park,
      categories: ['Accents'],
      fx: 51,
      colors: ['49DB6D', 'FF9123', '000000'],
      paletteId: 4,
      sx: 57,
      ix: 127,
    ),
    Preset(
      name: 'Windy Fall',
      description: 'A windy effect with fall colors.',
      icon: Icons.park,
      categories: ['Accents'],
      fx: 64,
      colors: ['990000', 'FF9123', '979797'],
      paletteId: 3,
      sx: 60,
      ix: 255,
    ),
    Preset(
      name: 'Coastal Calm',
      description: 'Soothing coastal colors.',
      icon: Icons.waves,
      categories: ['Accents'],
      fx: 75,
      colors: ['FFFFFF', 'FF0000', 'C0C0C0'],
      paletteId: 22,
      sx: 128,
      ix: 128,
    ),

    // **Holidays**
    Preset(
      name: 'Candy Cane',
      description: 'A festive candy cane pattern.',
      icon: Icons.star,
      categories: ['Holidays'],
      fx: 37,
      colors: ['FF0000', 'F9F7F5', '000000'],
      paletteId: 0,
      sx: 40,
      ix: 150,
    ),
    Preset(
      name: 'Candy Cane Flow',
      description: 'A flowing candy cane effect.',
      icon: Icons.star,
      categories: ['Holidays'],
      fx: 108,
      colors: ['FF0000', 'F9F7F5', '000000'],
      paletteId: 0,
      sx: 20,
      ix: 55,
    ),
    Preset(
      name: 'Christmas Seesaw',
      description: 'A seesaw effect with Christmas colors.',
      icon: Icons.star,
      categories: ['Holidays'],
      fx: 113,
      colors: ['FF0000', 'FFFFFF', '08FF00'],
      paletteId: 5,
      sx: 30,
      ix: 133,
    ),
    Preset(
      name: 'Tinsel Twinkle',
      description: 'A twinkling tinsel effect for Christmas.',
      icon: Icons.star,
      categories: ['Holidays'],
      fx: 80,
      colors: ['FF0000', '08FF00', 'C3AA1B'],
      paletteId: 5,
      sx: 105,
      ix: 190,
    ),
    Preset(
      name: 'Christmas Fade',
      description: 'A fading effect with Christmas colors.',
      icon: Icons.star,
      categories: ['Holidays'],
      fx: 105,
      colors: ['08FF00', 'FF0000', '000000'],
      paletteId: 0,
      sx: 40,
      ix: 220,
    ),
    Preset(
      name: 'Snowfall',
      description: 'A gentle snowfall effect.',
      icon: Icons.ac_unit,
      categories: ['Holidays'],
      fx: 74,
      colors: ['36A4FF', '99DBFF', '000000'],
      paletteId: 3,
      sx: 83,
      ix: 234,
    ),
    Preset(
      name: 'Christmas Stack',
      description: 'A stacking effect with Christmas colors.',
      icon: Icons.star,
      categories: ['Holidays'],
      fx: 44,
      colors: ['FFFFFF', '000000', '004A23'],
      paletteId: 53,
      sx: 20,
      ix: 60,
    ),
    Preset(
      name: 'Christmas Itch',
      description: 'An itchy effect with Christmas colors.',
      icon: Icons.star,
      categories: ['Holidays'],
      fx: 73,
      colors: ['FFFFFF', '000000', 'FF0000'],
      paletteId: 53,
      sx: 5,
      ix: 128,
    ),
    Preset(
      name: 'Mistletoe Drift',
      description: 'A drifting mistletoe effect.',
      icon: Icons.star,
      categories: ['Holidays'],
      fx: 105,
      colors: ['00FF00', 'FF0000', '000000'],
      paletteId: 0,
      sx: 70,
      ix: 255,
    ),
    Preset(
      name: 'Christmas Android fun',
      description: 'A fun Android effect with Christmas colors.',
      icon: Icons.star,
      categories: ['Holidays'],
      fx: 27,
      colors: ['FFFFFF', 'FF0000', '000000'],
      paletteId: 2,
      sx: 133,
      ix: 147,
    ),
    Preset(
      name: 'Fireworks Canada',
      description: 'Fireworks for Canada Day.',
      icon: Icons.celebration,
      categories: ['Holidays'],
      fx: 90,
      colors: ['FFFFFF', 'FF0000', '0000FF'],
      paletteId: 2,
      sx: 50,
      ix: 128,
    ),
    Preset(
      name: 'Fireworks 4th July',
      description: 'Fireworks for the 4th of July.',
      icon: Icons.celebration,
      categories: ['Holidays'],
      fx: 90,
      colors: ['FF0000', '000000', '0000FF'],
      paletteId: 5,
      sx: 50,
      ix: 128,
    ),
    Preset(
      name: 'Fireworks',
      description: 'A general fireworks effect.',
      icon: Icons.celebration,
      categories: ['Holidays'],
      fx: 90,
      paletteId: 11,
      sx: 80,
      ix: 128,
    ),
    Preset(
      name: 'Cinco de Mayo',
      description: 'A festive effect for Cinco de Mayo.',
      icon: Icons.celebration,
      categories: ['Holidays'],
      fx: 54,
      colors: ['FF0000', '08FF00', 'FFFFFF'],
      paletteId: 0,
      sx: 90,
      ix: 100,
    ),
    Preset(
      name: 'Easter Twinkle',
      description: 'A twinkling effect for Easter.',
      icon: Icons.egg,
      categories: ['Holidays'],
      fx: 80,
      colors: ['FF0000', '0000FF', '3D3D3D'],
      paletteId: 59,
      sx: 60,
      ix: 200,
    ),
    Preset(
      name: 'Easter Hop',
      description: 'A hopping effect for Easter.',
      icon: Icons.egg,
      categories: ['Holidays'],
      fx: 115,
      colors: ['FEFFF5', '000000', '000000'],
      paletteId: 37,
      sx: 190,
      ix: 212,
    ),
    Preset(
      name: 'Valentine Blush',
      description: 'A blushing effect for Valentine\'s Day.',
      icon: Icons.favorite,
      categories: ['Holidays'],
      fx: 46,
      colors: ['FF0000', 'FF00FF', '000000'],
      paletteId: 0,
      sx: 255,
      ix: 225,
    ),
    Preset(
      name: 'Heartbeat',
      description: 'A heartbeat effect for Valentine\'s Day.',
      icon: Icons.favorite,
      categories: ['Holidays'],
      fx: 100,
      colors: ['FF0000', 'FF7A78', 'FF69B4'],
      paletteId: 0,
      sx: 10,
      ix: 10,
    ),
    Preset(
      name: 'St. Patrick Bounce',
      description: 'A bouncing effect for St. Patrick\'s Day.',
      icon: Icons.local_florist,
      categories: ['Holidays'],
      fx: 86,
      colors: ['08FF00', '008C41', '004A23'],
      paletteId: 0,
      sx: 207,
      ix: 113,
    ),
    Preset(
      name: 'Romantic Sweep',
      description: 'A sweeping romantic effect.',
      icon: Icons.favorite,
      categories: ['Holidays'],
      fx: 6,
      colors: ['FF0000', 'FF00FF', '000000'],
      paletteId: 0,
      sx: 120,
      ix: 90,
    ),

    // **Sports**
    Preset(
      name: 'Calgary Flames',
      description: 'Colors of the Calgary Flames.',
      icon: Icons.sports_hockey,
      categories: ['Sports'],
      fx: 54,
      colors: ['D2001C', 'FAA719', 'FFFFFF'],
      paletteId: 0,
      sx: 70,
      ix: 70,
      c3: 25,
    ),
    Preset(
      name: 'Calgary Flames 2',
      description: 'Another effect for the Calgary Flames.',
      icon: Icons.sports_hockey,
      categories: ['Sports'],
      fx: 115,
      colors: ['D2001C', 'FAA719', 'FFFFFF'],
      paletteId: 5,
      sx: 90,
      ix: 40,
    ),
    Preset(
      name: 'Toronto Maple Leafs',
      description: 'Colors of the Toronto Maple Leafs.',
      icon: Icons.sports_hockey,
      categories: ['Sports'],
      fx: 115,
      colors: ['00205B', 'FFFFFF', '000000'],
      paletteId: 5,
      sx: 90,
      ix: 40,
    ),
    Preset(
      name: 'Los Angeles Lakers',
      description: 'Colors of the Los Angeles Lakers.',
      icon: Icons.sports_basketball,
      categories: ['Sports'],
      fx: 54,
      colors: ['552582', 'FDB927', '000000'],
      paletteId: 0,
      sx: 70,
      ix: 70,
      c3: 25,
    ),
    Preset(
      name: 'Boston Celtics',
      description: 'Colors of the Boston Celtics.',
      icon: Icons.sports_basketball,
      categories: ['Sports'],
      fx: 15,
      colors: ['007A33', 'FFFFFF', '000000'],
      paletteId: 0,
      sx: 50,
      ix: 100,
    ),

    // **Events**
    Preset(
      name: 'Police Lights',
      description: 'Flashing police lights effect.',
      icon: Icons.local_police,
      categories: ['Events'],
      fx: 50,
      colors: ['FF0000', '0000FF', '3D3D3D'],
      paletteId: 0,
      sx: 220,
      ix: 65,
    ),
    Preset(
      name: 'Radiant Sway',
      description: 'A radiant swaying effect.',
      icon: Icons.waves,
      categories: ['Events'],
      fx: 111,
      colors: ['FF0000', '000000', 'B700B7'],
      paletteId: 1,
      sx: 30,
      ix: 30,
    ),
    Preset(
      name: 'Glitter Candy',
      description: 'A glittering candy effect.',
      icon: Icons.cake,
      categories: ['Events'],
      fx: 87,
      colors: ['FFFFFF', '52A1FA', 'C0C0C0'],
      paletteId: 61,
      sx: 30,
      ix: 55,
    ),
    Preset(
      name: 'Lavender Fields',
      description: 'A calming lavender field effect.',
      icon: Icons.local_florist,
      categories: ['Events'],
      fx: 15,
      colors: ['800080', 'FFA1BD', '00FFFF'],
      paletteId: 0,
      sx: 50,
      ix: 100,
    ),
    Preset(
      name: 'Ruby Greenway',
      description: 'A ruby and green pathway effect.',
      icon: Icons.directions,
      categories: ['Events'],
      fx: 13,
      colors: ['FF0000', '00FF00', '000000'],
      paletteId: 0,
      sx: 10,
      ix: 25,
    ),
    Preset(
      name: 'Aurora Winter',
      description: 'An aurora effect for winter.',
      icon: Icons.nights_stay,
      categories: ['Events'],
      fx: 38,
      colors: ['FF0000', '0000FF', '000000'],
      paletteId: 51,
      sx: 16,
      ix: 80,
    ),
    Preset(
      name: 'Birthday Party',
      description: 'A festive birthday party effect.',
      icon: Icons.cake,
      categories: ['Events'],
      fx: 94,
      paletteId: 0,
      sx: 128,
      ix: 0,
    ),
    Preset(
      name: 'Circus',
      description: 'A vibrant circus effect.',
      icon: Icons.attractions,
      categories: ['Events'],
      fx: 54,
      colors: ['FFFFFF', '0000FF', 'FF0000'],
      paletteId: 0,
      sx: 40,
      ix: 0,
    ),
    Preset(
      name: 'Fire Invite',
      description: 'A fiery invitation effect.',
      icon: Icons.local_fire_department,
      categories: ['Events'],
      fx: 66,
      colors: ['FFC800', 'FF3700', '000000'],
      paletteId: 4,
      sx: 45,
      ix: 170,
      c3: 25,
    ),
    Preset(
      name: 'Blue Sine',
      description: 'A blue sine wave effect.',
      icon: Icons.waves,
      categories: ['Events'],
      fx: 92,
      colors: ['FFFFFF', '0000FF', '000000'],
      paletteId: 0,
      sx: 20,
      ix: 30,
      c3: 25,
    ),
    Preset(
      name: 'LED Highway',
      description: 'A highway effect with LED colors.',
      icon: Icons.directions_car,
      categories: ['Events'],
      fx: 112,
      colors: ['FF0000', '0000FF', '08FF00'],
      paletteId: 5,
      sx: 20,
      ix: 170,
    ),
    Preset(
      name: 'Witch\'s Cauldron',
      description: 'A spooky cauldron effect.',
      icon: Icons.local_drink,
      categories: ['Events'],
      fx: 76,
      colors: ['FF0000', '08FF00', 'FFFFFF'],
      paletteId: 51,
      sx: 45,
      ix: 240,
    ),
    Preset(
      name: 'Jack-o\'-Lanterns',
      description: 'A Halloween jack-o\'-lantern effect.',
      icon: Icons.local_florist,
      categories: ['Events'],
      fx: 49,
      colors: ['800080', '905A00', 'FF1493'],
      paletteId: 0,
      sx: 128,
      ix: 160,
    ),
    Preset(
      name: 'Pumpkin Waves',
      description: 'A wavy pumpkin effect for Halloween.',
      icon: Icons.local_florist,
      categories: ['Events'],
      fx: 67,
      colors: ['FFA000', 'FF0000', '000000'],
      paletteId: 3,
      sx: 21,
      ix: 255,
    ),
    Preset(
      name: 'Pumpkin Candles',
      description: 'A candle-like effect for Halloween pumpkins.',
      icon: Icons.local_florist,
      categories: ['Events'],
      fx: 49,
      colors: ['800080', '905A00', 'FF1493'],
      paletteId: 0,
      sx: 128,
      ix: 160,
    ),

    // **Special Preset**
    Preset(
      name: 'OFF',
      description: 'Turns off the lights.',
      icon: Icons.power_off,
      categories: ['Special'],
      fx: 0,
      colors: ['000000', '08FF00', '0000FF'],
      paletteId: 0,
      sx: 30,
      ix: 30,
    ),
  ];

  static List<Preset> get presets => _presets;

  static List<Preset> getPresetsByCategory(String category) {
    if (category == 'All') {
      return _presets;
    }
    return _presets.where((preset) => preset.categories.contains(category)).toList();
  }
}